import { TrackType } from 'shared/types/Track';

const tracks: TrackType[] = [
  {
    id: 1,
    title: 'Bohemian Rhapsody',
    author: 'Queen',
    imageUrl: 'https://picsum.photos/300/300?random=1',
    duration: 354,
    isPremium: false,
    rating: 4.9,
    genre: 'Rock',
  },
  {
    id: 2,
    title: 'Blinding Lights',
    author: 'The Weeknd',
    imageUrl: 'https://picsum.photos/300/300?random=2',
    duration: 200,
    isPremium: true,
    rating: 4.7,
    genre: 'Pop',
  },
  {
    id: 3,
    title: 'Shape of You',
    author: 'Ed Sheeran',
    imageUrl: 'https://picsum.photos/300/300?random=3',
    duration: 233,
    isPremium: false,
    rating: 4.5,
    genre: 'Pop',
  },
  {
    id: 4,
    title: 'Smooth Criminal',
    author: 'Michael Jackson',
    imageUrl: 'https://picsum.photos/300/300?random=4',
    duration: 258,
    isPremium: true,
    rating: 4.8,
    genre: 'Pop',
  },
  {
    id: 5,
    title: 'Stairway to Heaven',
    author: 'Led Zeppelin',
    imageUrl: 'https://picsum.photos/300/300?random=5',
    duration: 482,
    isPremium: false,
    rating: 4.9,
    genre: 'Rock',
  },
  {
    id: 6,
    title: 'Bad Guy',
    author: 'Billie Eilish',
    imageUrl: 'https://picsum.photos/300/300?random=6',
    duration: 194,
    isPremium: true,
    rating: 4.3,
    genre: 'Electropop',
  },
  {
    id: 7,
    title: 'Yesterday',
    author: 'The Beatles',
    imageUrl: 'https://picsum.photos/300/300?random=7',
    duration: 125,
    isPremium: false,
    rating: 4.7,
    genre: 'Rock',
  },
  {
    id: 8,
    title: 'Uptown Funk',
    author: 'Mark Ronson ft. Bruno Mars',
    imageUrl: 'https://picsum.photos/300/300?random=8',
    duration: 270,
    isPremium: true,
    rating: 4.6,
    genre: 'Funk',
  },
  {
    id: 9,
    title: 'Smells Like Teen Spirit',
    author: 'Nirvana',
    imageUrl: 'https://picsum.photos/300/300?random=9',
    duration: 301,
    isPremium: false,
    rating: 4.8,
    genre: 'Grunge',
  },
  {
    id: 10,
    title: 'Levitating',
    author: 'Dua Lipa',
    imageUrl: 'https://picsum.photos/300/300?random=10',
    duration: 203,
    isPremium: true,
    rating: 4.4,
    genre: 'Pop',
  },
  {
    id: 11,
    title: 'Take on Me',
    author: 'a-ha',
    imageUrl: 'https://picsum.photos/300/300?random=11',
    duration: 225,
    isPremium: false,
    rating: 4.6,
    genre: 'Synth-pop',
  },
  {
    id: 12,
    title: 'Industry Baby',
    author: 'Lil Nas X',
    imageUrl: 'https://picsum.photos/300/300?random=12',
    duration: 212,
    isPremium: true,
    rating: 4.2,
    genre: 'Hip-Hop',
  },
];

export const getTrackList = async () => {
  return new Promise<TrackType[]>(resolve => {
    setTimeout(() => {
      resolve(tracks);
    }, 1500);
  });
};
